# Generated by Django 5.2.1 on 2025-12-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='kirish')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='bosh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
